export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';
export const FETCH_BEST_PRODUCTS = 'FETCH_BEST_PRODUCTS';

export const API_ENDPOINT = 'http://localhost:8082/api';
